# Generated by Django 4.1.2 on 2022-11-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_options_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': 'Maxsulot'},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=2, upload_to='product'),
            preserve_default=False,
        ),
    ]
